/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, IStateStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'PeriodicJob': CronHandler<{ topic: 'cron-ticked'; data: { message: string } }>
    'CheckStateChange': EventHandler<{ key: string; expected: string }, never>
    'SetStateChange': EventHandler<{ message: string }, { topic: 'check-state-change'; data: { key: string; expected: string } }>
    'ApiTrigger': ApiRouteHandler<{ nome: string; idade: number; email: string; telefone: string }, ApiResponse<200, { nome: string; idade: number; email: string; telefone: string }>, { topic: 'test-state'; data: { message: string } }>
    'TimeEvent': EventHandler<{ message: string }, never>
    'HelloWorld': ApiRouteHandler<{ nome: string }, ApiResponse<200, { phrase: string }>, { topic: 'saudacao'; data: { message: string } }>
  }
}